### ISSUE TITLE
Finalize v1.0.0

### ISSUE THREAD

**Issue by Carl-Hugo** [ForEvolve/MetaPackages#2]
*Notes to self*

**To investigate**
- ~~Move the meta package to the main solution?~~
- ~~Otherwise have VSTS trigger the meta build after the `master-CI` build is released to MyGet~~

**TODO**
- [x] Rename the project `ForEvolve.App`
- [x] Add `ForEvolve.Pdf` and `ForEvolve.Pdf.Abstractions` to the meta package.
- [x] Make sure the project include `ForEvolve.AspNetCore.Localization`
- [x] ~~Create a build that will be triggered by a successful `ForEvolve.AspNetCore.Localization` build that starts a build of the `ForEvolve.App` package. If possible limit the build to the `ForEvolve.App` project and not the entire solution.~~
- [x] ~~Have VSTS trigger the meta build after the `master-CI` build is released to MyGet~~
- [x] Move the "meta build" to the `ForEvolve-Framework` VSTS project
- [x] Update readme
- [x] Create a release definition
- [x] Deploy `ForEvolve.App` v1.0.0-RC-1
- [x] Test it out
- [x] Deploy `ForEvolve.App` v1.0.0 to NuGet
